version: "3.9"

services:
  postgresql:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hack_api_user
      - POSTGRES_DB=hack_api
      - POSTGRES_HOST_AUTH_METHOD=trust
    logging:
      driver: none

volumes:
  db_volume: